name: Build docs

on:
  workflow_call:

jobs:
  build:
    name: Build Docs
    container: python:3.12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Git config
        run: |
          git config --system --add safe.directory /__w/certwrangler/certwrangler
      - name: Install build deps
        run: |
          apt update
          apt install -y graphviz graphviz-dev
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[docs,dev]
      - name: Build
        run: |
          make -C docs html
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/build/html/
